# Generated by Django 5.0.3 on 2024-03-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inten",
            name="data_pedido",
        ),
    ]
