# Generated by Django 5.0.3 on 2024-03-25 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_inten_data_pedido"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_nome", models.CharField(max_length=60)),
                ("email", models.CharField(max_length=100)),
                ("data_pedida", models.DateTimeField(default=datetime.datetime.now)),
                ("quantidade_pedida", models.IntegerField()),
                ("pedido", models.BooleanField()),
            ],
        ),
    ]
