# Generated by Django 5.0.3 on 2024-03-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_usuarios"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarios",
            name="quantidade_pedida",
            field=models.IntegerField(default=0),
        ),
    ]
