# Generated by Django 5.0.3 on 2024-03-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_usuarios_quantidade_pedida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarios",
            name="quantidade_pedida",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
