# Generated by Django 5.0.3 on 2024-03-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_usuarios_quantidade_pedida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarios",
            name="pedido",
            field=models.BooleanField(default=False),
        ),
    ]
