# Generated by Django 5.0.3 on 2024-03-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_usuarios_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarios",
            name="pedido",
            field=models.CharField(max_length=60),
        ),
    ]
