# Generated by Django 5.0.3 on 2024-03-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_usuarios_pedido"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_nome", models.CharField(max_length=60)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("data_pedida", models.DateTimeField(auto_now_add=True)),
                (
                    "itens_pedidos",
                    models.ManyToManyField(related_name="usuarios", to="app.inten"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Usuarios",
        ),
    ]
