# Generated by Django 5.0.1 on 2024-03-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_rename_inten_iten"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iten",
            name="quantidade",
        ),
        migrations.AddField(
            model_name="usuario",
            name="quantidade",
            field=models.IntegerField(default=""),
        ),
    ]
