# Generated by Django 5.0.1 on 2024-03-27 14:21

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_rename_inten_iten"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iten",
            name="quantidade",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=0, max_length=128, region=None
            ),
        ),
    ]
