# Generated by Django 5.0.1 on 2024-03-26 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_remove_iten_quantidade_usuario_quantidade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="quantidade",
        ),
        migrations.AddField(
            model_name="iten",
            name="quantidade",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.iten"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.usuario"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="usuario",
            name="itens_pedidos",
            field=models.ManyToManyField(through="app.Pedido", to="app.iten"),
        ),
    ]
