# Generated by Django 5.2 on 2026-05-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_iten_quantidade_alter_usuario_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='data_pedida',
            new_name='current_date',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='itens_pedidos',
            new_name='ordered_items',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='telefone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='user_nome',
            new_name='user_name',
        ),
    ]
