# Generated by Django 5.2 on 2026-05-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_data_pedida_usuario_current_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iten',
            old_name='ativo',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='iten',
            old_name='quantidade',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='iten',
            old_name='nome',
            new_name='name',
        ),
    ]
