# Generated by Django 5.0.1 on 2024-03-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_usuario_quantidade_iten_quantidade_pedido_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iten",
            name="quantidade",
        ),
    ]
