# Generated by Django 5.0.1 on 2024-03-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_iten_quantidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iten",
            name="quantidade",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
