# Generated by Django 5.0.1 on 2024-03-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_iten_quantidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="quantidade",
            field=models.IntegerField(default=1),
        ),
    ]
