# Generated by Django 5.0.1 on 2024-03-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_pedido_quantidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iten",
            name="quantidade",
            field=models.IntegerField(default=1),
        ),
    ]
