# Generated by Django 5.0.1 on 2024-03-26 18:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_alter_iten_quantidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iten",
            name="quantidade",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="data_pedida",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, default="", max_length=128, region=None
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pedido",
            unique_together={("usuario", "item")},
        ),
    ]
