# Generated by Django 5.0.1 on 2024-03-26 19:01

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_alter_usuario_telefone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iten",
            name="quantidade",
        ),
        migrations.AddField(
            model_name="usuario",
            name="quantidade",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="data_pedida",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="itens_pedidos",
            field=models.ManyToManyField(related_name="usuarios", to="app.iten"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="", max_length=128, region=None
            ),
        ),
        migrations.DeleteModel(
            name="Pedido",
        ),
    ]
