# Generated by Django 5.0.1 on 2024-03-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_remove_iten_quantidade_usuario_quantidade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="quantidade",
        ),
        migrations.AddField(
            model_name="iten",
            name="quantidade",
            field=models.IntegerField(default=0),
        ),
    ]
