# Generated by Django 5.0.1 on 2024-03-27 13:35

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_remove_usuario_quantidade_iten_quantidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=0, max_length=128, region=None
            ),
        ),
    ]
